name: Website deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed "s/DATEHERE/$(date)/g" public/index.html > public/index.new ; mv public/index.new public/index.html
          unzip public/oldicons/icons.zip -d public/oldicons/icons
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GH_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: hbs18-18ff5
          channelId: live